# Generated by Django 2.2.28 on 2023-07-16 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaapp', '0002_auto_20230716_0236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persons',
            options={'managed': True},
        ),
    ]
