# Generated by Django 2.2.28 on 2023-07-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaapp', '0006_auto_20230717_1840'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users_gesta',
            table='USERS',
        ),
    ]
