# Generated by Django 2.2.28 on 2023-07-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaapp', '0008_auto_20230717_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneeCaisseBack',
            fields=[
                ('n_journee', models.IntegerField(primary_key=True, serialize=False)),
                ('date_ouvert', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('ouvertepar', models.CharField(blank=True, max_length=20, null=True)),
                ('cloturepar', models.CharField(blank=True, max_length=20, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('fond_caisse_ouvert', models.FloatField(blank=True, null=True)),
                ('fond_caisse_suivant', models.FloatField(blank=True, null=True)),
                ('entree_caisse', models.FloatField(blank=True, null=True)),
                ('sortie_caisse', models.FloatField(blank=True, null=True)),
                ('retrait_caisse', models.FloatField(blank=True, null=True)),
                ('cloture', models.SmallIntegerField(blank=True, null=True)),
                ('caisse', models.IntegerField(blank=True, null=True)),
                ('source', models.IntegerField(blank=True, null=True)),
                ('total_benefice', models.FloatField(blank=True, null=True)),
                ('ecart', models.FloatField(blank=True, null=True)),
                ('total_recup', models.FloatField(blank=True, null=True)),
                ('archive', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'journee_caisse_back',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TComptoirPBack',
            fields=[
                ('n_facture', models.IntegerField(primary_key=True, serialize=False)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('valide', models.SmallIntegerField(blank=True, null=True)),
                ('journee', models.DateField(blank=True, null=True)),
                ('fondcaisse', models.FloatField(blank=True, null=True)),
                ('caisse', models.IntegerField(blank=True, null=True)),
                ('client', models.IntegerField(blank=True, null=True)),
                ('num_table', models.FloatField(blank=True, null=True)),
                ('num_payement', models.IntegerField(blank=True, null=True)),
                ('creepar', models.CharField(blank=True, max_length=20, null=True)),
                ('validepar', models.CharField(blank=True, max_length=20, null=True)),
                ('mode', models.SmallIntegerField(blank=True, null=True)),
                ('montant_w', models.FloatField(blank=True, null=True)),
                ('montant_tva', models.FloatField(blank=True, null=True)),
                ('m_tmbre', models.FloatField(blank=True, null=True)),
                ('type_versement', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.IntegerField(blank=True, null=True)),
                ('lclient', models.CharField(blank=True, max_length=60, null=True)),
                ('vendeur', models.DateTimeField(blank=True, null=True)),
                ('facture', models.IntegerField(blank=True, null=True)),
                ('detailpartennaire', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_comptoir_p_back',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
